DISPLAY_HEIGHT = 720
DISPLAY_WIDTH = 480
DISPLAY = (DISPLAY_HEIGHT, DISPLAY_WIDTH)

X_SHIP = 0.0
Y_SHIP = 0.0

RAND_REC_X = 2
RAND_REC_Y = 2

MOVING_LEFT = False
MOVING_RIGHT = False
MOVING_UP = False
MOVING_DOWN = False

COLLISION_DETECTED = False
NUMBER_OF_COLLISIONS = 0

BACK_RED = 0.0
BACK_GREEN = 1.0
BACK_BLUE = 0.0

RANDOM_POSITIONS = [2, 2, 2, 2]

SPEED = 0.06
